version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: asml-org
      DOCKER_INFLUXDB_INIT_BUCKET: machine_metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-token
    networks:
      - asml-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: my-super-token
      INFLUXDB_ORG: asml-org
      INFLUXDB_BUCKET: machine_metrics
    networks:
      - asml-net

  generator:
    build: ./generator
    depends_on:
      - backend
    networks:
      - asml-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - asml-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - asml-net

networks:
  asml-net: